### ISSUE TITLE
Need 7 day of the week in the database

### ISSUE THREAD

**Issue by h4ms-codex** [ICS2609-2ITI-2024/tomconnect#45]
Based on the image, kailangan natin yung Monday kaso wala tayong days sa database time lang meron.

![Screenshot 2024-05-06 142658](https://github.com/ICS2609-2ITI-2024/tomconnect/assets/118837080/15ce9add-3478-4451-bf3c-bd2b95076197)

**Comment by wjamesdevera** [comment]
may feature na pala php for that read:
https://stackoverflow.com/questions/1385801/how-can-i-get-the-day-of-a-specific-date-with-php
